// This test should fail with an exception.